### ISSUE TITLE
Asset :- This should be last location 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#890]
![image](https://user-images.githubusercontent.com/79301742/113666163-724bd800-96cc-11eb-81c5-18b8b6164fda.png)

**Comment by AmitojSingh1** [comment]
@rashmi0301 I have fixed this issue please test it.

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/113972869-03e85080-9859-11eb-92fa-f713a52df803.png)

Not fixed @AmitojSingh1

**Comment by rashmi0301** [comment]
Now its done
